# https://doc.rust-lang.org/cargo/reference/manifest.html
[build]
target-dir = "/tmp/rustTmp/target2"
# rustflags = ["--cfg", "unsound_local_offset"] # local time
# rustflags = ["-Zthreads=32", "-Clink-arg=-fuse-ld=mold"] # nightly + mold linker
# jobs = 16 # cpus
# rustc-wrapper = "sccache" # cache rustc


[env]



[profile.release]
opt-level = 'z'
lto = "thin"
# codegen-units = 8
panic = "abort"
strip = true

[profile.dev]
# opt-level = 1
# faster compile
split-debuginfo = "unpacked"
# strip = "debuginfo"
incremental = false





